version: "2.8"
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - "3306:3306"
        volumes:
          - ./mysql-data:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=admin123
        networks:
          - mynetwork

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
          - "8081:80"
        environment:
          - PMA_HOST=mysql
          - PMA_USER=root
          - PMA_PASSWORD=admin123
          - MYSQL_ROOT_PASSWORD=admin123
        depends_on:
          - mysql
        networks:
          - mynetwork

volumes:
    mysql-data:

networks:
    mynetwork:
      